from backend.models.condition_policy import ConditionPolicy

pregnancy_policy = ConditionPolicy(
    condition_id="pregnancy",
    blocked_ingredients=[
        "raw fish", "sashimi", "sushi", "raw tuna", "raw salmon",
        "raw oyster", "raw clam", "raw mussel", "raw shellfish",
        "steak tartare", "beef tartare", "tuna tartare",
        "carpaccio", "bresaola",  
        "raw chicken", "raw pork",
        "raw egg", "raw egg white", "raw egg yolk",
        "caesar dressing",      
        "hollandaise",           
        "bearnaise",
        "mayonnaise",            
        "aioli",                 
        "mousse",               
        "tiramisu",              
        "eggnog",                
        "shark", "shark fin",
        "swordfish",
        "king mackerel",
        "tilefish",
        "orange roughy",
        "bigeye tuna",
        "marlin",
        "alcohol", "wine", "red wine", "white wine", "champagne", "prosecco",
        "beer", "ale", "lager", "cider",
        "spirits", "vodka", "whiskey", "rum", "gin", "tequila", "brandy",
        "sake", "soju", "liqueur",
        "wine sauce", "beer batter", "coq au vin", "beef bourguignon",
        "flambe", "rum cake", "tiramisu",
        "liver", "chicken liver", "beef liver", "lamb liver",
        "liver pate", "pate", "foie gras",
        "unpasteurized cheese", "raw milk cheese",
        "brie", "camembert",        
        "roquefort", "gorgonzola", "stilton", "blue cheese",
        "queso fresco", "queso blanco", "queso panela",
        "feta",                      
        "soft goat cheese", "chevre",
    ],
    blocked_tags=[
        "raw", "undercooked", "rare", "blue_rare",
        "raw_fish", "raw_shellfish", "raw_egg",
        "unpasteurized", "unpasteurised",
        "high_mercury",
        "alcohol_based", "flambeed",
    ],
    caution_ingredients=[
        "smoked salmon", "lox", "gravlax", "smoked trout",
        "cold-smoked fish", "smoked seafood",
        "deli meat", "deli turkey", "deli ham", "lunch meat",
        "cold cuts", "bologna", "salami", "pepperoni", "prosciutto",
        "hot dog", "frankfurter", "wiener",
        "tuna", "canned tuna", "albacore tuna",
        "halibut", "mahi mahi", "grouper", "snapper", "sea bass",
        "unpasteurized juice", "raw cider", "fresh-pressed juice",
        "sprouts", "alfalfa sprouts", "bean sprouts", "clover sprouts",
        "radish sprouts", "mung bean sprouts",
        "caffeine", "espresso", "energy drink",
    ],
    caution_tags=[
        "runny_egg", "soft_cooked_egg", "poached_egg",
        "unclear_pasteurization", "cold_smoked",
        "may_contain_listeria", "high_caffeine",
        "cured_not_cooked", "medium_rare", "pink_inside",
        "refrigerated_ready_to_eat",
    ],
    uncertainty_penalty=0.20,
)
